In [2]:
# install libraries
!pip install kaggle
import kaggle

Requirement already satisfied: kaggle in c:\users\asus\anaconda3\lib\site-packages (1.7.4.2)
Requirement already satisfied: bleach in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (4.1.0)
Requirement already satisfied: certifi>=14.05.14 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2024.7.4)
Requirement already satisfied: charset-normalizer in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.0.4)
Requirement already satisfied: idna in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (3.7)
Requirement already satisfied: protobuf in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (3.20.3)
Requirement already satisfied: python-dateutil>=2.5.3 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: python-slugify in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (5.0.2)
Requirement already satisfied: requests in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.32.2)
Requirement already satisfied: setuptools>=21.0.0 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (69.5.1)
Requirement already satisfied: six>=1.10 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: text-unidecode in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (1.3)
Requirement already satisfied: tqdm in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (4.66.4)
Requirement already satisfied: urllib3>=1.15.1 in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (2.2.2)
Requirement already satisfied: webencodings in c:\users\asus\anaconda3\lib\site-packages (from kaggle) (0.5.1)
Requirement already satisfied: packaging in c:\users\asus\anaconda3\lib\site-packages (from bleach->kaggle) (23.2)
Requirement already satisfied: colorama in c:\users\asus\anaconda3\lib\site-packages (from tqdm->kaggle) (0.4.6)

In [4]:
# download dataset from kaggle
!kaggle datasets download -d ankitbansal06/retail-orders

Dataset URL: https://www.kaggle.com/datasets/ankitbansal06/retail-orders
License(s): CC0-1.0
retail-orders.zip: Skipping, found more recently modified local copy (use --force to force download)

In [10]:
#extract file from zip file
import zipfile
zip_ref = zipfile.ZipFile("retail-orders.zip") 
zip_ref.extractall() # extract file to dir
zip_ref.close() # close file

In [22]:
# read data from the file and  handle null value
import pandas as pd
df = pd.read_csv('orders.csv',na_values=['Not Available','unknown'])
df

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3

In [24]:
# check distinct values
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [36]:
# rename columns names ..  make them lower case and replace sapece with underscore
df.rename(columns={'Order Id':'order_id','City':'city'})
# or
df.columns = df.columns.str.lower() # with this method we can convert all columns names into lowercase

In [44]:
df.columns= df.columns.str.replace(' ','_') # with this method we can convert blank space with underscore
df.columns

Index(['order_id', 'order_date', 'ship_mode', 'segment', 'country', 'city',
       'state', 'postal_code', 'region', 'category', 'sub_category',
       'product_id', 'cost_price', 'list_price', 'quantity',
       'discount_percent'],
      dtype='object')

In [52]:
# dervive new columns discount , sale price and profit
# 1. discount column >> list_price * discount_percent/100
df['discount'] = df['list_price']*df['discount_percent']/100 
df['discount']

0        5.2
1       21.9
2        0.5
3       19.2
4        1.0
        ...
9989     1.2
9990     3.6
9991     5.2
9992     0.9
9993     7.2
Name: discount, Length: 9994, dtype: float64

In [58]:
# 2. sale column >> list_price - discount
df['sale_price'] = df['list_price']-df['discount']
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,30,30,3,4,1.2,28.8
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,70,90,2,4,3.6,86.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,220,260,2,2,5.2,254.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,30,30,4,3,0.9,29.1
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,210,240,2,3,7.2,232.8

In [62]:
# 3. profit >> sale_price - cost_price
df['profit'] = df['sale_price'] - df['cost_price']
df['profit']

0        14.8
1       108.1
2        -0.5
3       160.8
4        -1.0
        ...
9989     -1.2
9990     16.4
9991     34.8
9992     -0.9
9993     22.8
Name: profit, Length: 9994, dtype: float64

In [72]:
# convert order date from object data type to datetime
df['order_date']= pd.to_datetime(df['order_date'],format='%Y-%m-%d')# this is the format of ur table date colum
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [78]:
# dropping unnessary  columns like discount_percent,cost_price,list_price
df.drop(columns=['list_price','discount_percent','cost_price']) # after it will still show in df 
# to avoid this we have to use inplace = true
df.drop(columns=['list_price','discount_percent','cost_price'],inplace=True)

In [80]:
df

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,quantity,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,2,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,5,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,2,1.0,19.0,-1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9989,9990,2023-02-18,Second Class,Consumer,United States,Miami,Florida,33180,South,Furniture,Furnishings,FUR-FU-10001889,3,1.2,28.8,-1.2
9990,9991,2023-03-17,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Furniture,Furnishings,FUR-FU-10000747,2,3.6,86.4,16.4
9991,9992,2022-08-07,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Technology,Phones,TEC-PH-10003645,2,5.2,254.8,34.8
9992,9993,2022-11-19,Standard Class,Consumer,United States,Costa Mesa,California,92627,West,Office Supplies,Paper,OFF-PA-10004041,4,0.9,29.1,-0.9
9993,9994,2022-07-17,Second Class,Consumer,United States,Westminster,California,92683,West,Office Supplies,Appliances,OFF-AP-10002684,2,7.2,232.8,22.8

In [ ]:
# note
'''
In Pandas, inplace=True means that changes will be applied directly to the DataFrame without creating a new copy. Let’s break it down!

📝 What Happens Without inplace=True?
By default, Pandas functions like drop(), fillna(), or sort_values() return a new DataFrame with changes applied, leaving the original DataFrame unchanged.
'''

In [86]:
# load data into mysql using replace option
# install alchemy for mysql
!pip install sqlalchemy pymysql
#import alchemy
import sqlalchemy as sal

Requirement already satisfied: sqlalchemy in c:\users\asus\anaconda3\lib\site-packages (2.0.30)
Requirement already satisfied: pymysql in c:\users\asus\anaconda3\lib\site-packages (1.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\asus\anaconda3\lib\site-packages (from sqlalchemy) (3.0.1)

In [88]:
engine = sal.create_engine('mysql+pymysql://root:adi3321@localhost:3306/retail_orders')
conn = engine.connect()
print("Connected to MySQL successfully!")

Connected to MySQL successfully!

In [92]:
# load data into mysql using replace option
df.to_sql('df_orders',con=conn,index=False,if_exists='replace')

9994

In [94]:
# load data into mysql after droping the above table and after inserting new table
df.to_sql('df_orders',con=conn,index=False,if_exists='append')

9994